
export const dataImages = [
  {
    id: "1",
    url: "/models/images/s1.jpg",
    name: "宫崎骏AI",
    desc: "宫崎骏AI绘画",
    scale: { x: 0.8, y: 0.8, z: 0.8 },
    position: { x: -2.64, y: 1.29, z: -2.9 },
    rotation: { x: 0, y: 0, z: 0 },
    type: "picture",
  },
  {
    id: "2",
    url: "/models/images/c1.jpg",
    name: "猫人",
    desc: "信息描述",
    scale: { x: 0.8, y: 0.8, z: 0.8 },
    position: { x: 5.26, y: 1.48, z: -2.98 },
    rotation: { x: 0, y: 0, z: 0 },
    type: "picture",
  },
  {
    id: "3",
    url: "/models/images/AIGC.jpg",
    name: "AIGC",
    desc: "AIGC生成的图片",
    scale: { x: 1.35, y: 1, z: 0.85 },
    position: { x: -2, y: 1.32, z: 7.05 },
    rotation: { x: -3.14, y: 0, z: -3.14 },
    type: "picture",
  },
  {
    id: "4",
    url: "/models/images/c2.jpg",
    name: "cat2",
    desc: "AIGC生成的图片",
    scale: { x: 0.8, y: 0.8, z: 0.85 },
    position: { x: 1, y: 1.32, z: 1 },
    rotation: { x: 0, y: 0, z: 0 },
    type: "picture",
  },
  {
    id: "5",
    url: "/models/images/s2.jpg",
    name: "s2",
    desc: "AIGC生成的图片",
    scale: { x: 1, y: 0.45, z: 1 },
    position: { x: 6.4, y: 1.37, z: 6.94 },
    rotation: { x: -3.14, y: 0, z: -3.14 },
    type: "picture",
  },
  // {
  //   id: "6",
  //   url: "/models/images/s2.jpg",
  //   name: "s2",
  //   desc: "AIGC生成的图片",
  //   scale: { x: 1, y: 1, z: 1 },
  //   position: { x: 1, y: 1, z: 1 },
  //   rotation: { x: 0, y: 0, z: 0 },
  //   type: "picture",
  // }
]