
export const dataImages = [
  {
    id: "1",
    url: "/models/images/s1.jpg",
    name: "哈尔的移动城堡",
    desc: "宫崎骏AI绘画",
    scale: { x: 0.8, y: 0.8, z: 0.8 },
    position: { x: -3.17, y: 1.36, z: -3.0 },
    rotation: { x: 0, y: 0, z: 0 },
    type: "picture",
  },
  {
    id: "2",
    url: "/models/images/c1.jpg",
    name: "猫人",
    desc: "信息描述",
    scale: { x: 0.8, y: 0.8, z: 0.8 },
    position: { x: 5.26, y: 1.34, z: -2.98 },
    rotation: { x: 0, y: 0, z: 0 },
    type: "picture",
  },
  {
    id: "3",
    url: "/models/images/AIGC.jpg",
    name: "AIGC",
    desc: "AIGC生成的图片",
    scale: { x: 1.94, y: 1.41, z: 0.85 },
    position: { x: -2.09, y: 1.36, z: 7.05 },
    rotation: { x: -3.14, y: 0, z: -3.14 },
    type: "picture",
  },
  {
    id: "4",
    url: "/models/images/c2.jpg",
    name: "cat2",
    desc: "AIGC生成的图片",
    scale: { x: 0.8, y: 0.6, z: 0.85 },
    position: { x: 7.16, y: 1.34, z: -3.06 },
    rotation: { x: 0, y: 0, z: 0 },
    type: "picture",
  },
  {
    id: "5",
    url: "/models/images/s2.jpg",
    name: "丛林小屋",
    desc: "AIGC生成的图片",
    scale: { x: 1, y: 0.45, z: 1 },
    position: { x: 6.4, y: 1.37, z: 6.94 },
    rotation: { x: -3.14, y: 0, z: -3.14 },
    type: "picture",
  },
  {
    id: "6",
    url: "/models/images/sphere.jpg",
    name: "日月山河图",
    desc: "AIGC生成的图片",
    scale: { x: 0.87, y: 0.77, z: 1 },
    position: { x: -1.24, y: 1.37, z: -2.88 },
    rotation: { x: 0, y: 0, z: 0 },
    type: "picture",
  },
  {
    id: "7",
    url: "/models/images/idyllic1.jpg",
    name: "麦田里的守望者",
    desc: "AIGC生成的图片",
    scale: { x: 1, y: 0.8, z: 1 },
    position: { x: -4.13, y: 1.85, z: -7.97 },
    rotation: { x: 0, y: 0, z: 0 },
    type: "picture",
  },
  {
    id: "8",
    url: "/models/images/idyllic2.jpg",
    name: "田园风光",
    desc: "AIGC生成的图片",
    scale: { x: 1, y: 0.83, z: 1 },
    position: { x: -1.0, y: 1.88, z: -7.6 },
    rotation: { x: 0, y: 0, z: 0 },
    type: "picture",
  },
  {
    id: "9",
    url: "/models/images/s4.jpg",
    name: "梦幻星空",
    desc: "AIGC生成的图片",
    scale: { x: 0.9, y: 0.65, z: 1 },
    position: { x: 4.8, y: 1.82, z: -7.6 },
    rotation: { x: 0, y: 0, z: 0 },
    type: "picture",
  },
  {
    id: "10",
    url: "/models/images/s5.jpg",
    name: "山河图",
    desc: "AIGC生成的图片",
    scale: { x: 0.9, y: 0.79, z: 1 },
    position: { x: 7.6, y: 1.82, z: -7.99 },
    rotation: { x: 0, y: 0, z: 0 },
    type: "picture",
  },
]